// <auto-generated />
using AnaliseAcoes.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AnaliseAcoes.Persistence.Migrations
{
    [DbContext(typeof(AnaliseAcoesContext))]
    [Migration("20171010012658_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("AnaliseAcoes.Domain.Entities.Ativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Atividade");

                    b.Property<string>("NomePregao");

                    b.Property<string>("Sigla");

                    b.HasKey("Id");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("AnaliseAcoes.Domain.Entities.DadoFundamentalista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AtivoId");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.ToTable("DadosFundamentalistas");
                });

            modelBuilder.Entity("AnaliseAcoes.Domain.Entities.DadoFundamentalista", b =>
                {
                    b.HasOne("AnaliseAcoes.Domain.Entities.Ativo", "Ativo")
                        .WithMany("DadosFundamentalistas")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("AnaliseAcoes.Domain.ValueObjects.DadosGerais", "DadosGerais", b1 =>
                        {
                            b1.Property<int>("DadoFundamentalistaId");

                            b1.Property<decimal>("Cotacao")
                                .HasColumnName("Cotacao");

                            b1.Property<DateTime>("DataUltimaCotacao")
                                .HasColumnName("DataUltimaCotacao");

                            b1.Property<DateTime>("DataUltimoBalancoProcessado")
                                .HasColumnName("DataUltimoBalancoProcessado");

                            b1.Property<decimal>("MaiorCotacaoUltimoAno")
                                .HasColumnName("MaiorCotacaoUltimoAno");

                            b1.Property<decimal>("MenorCotacaoUltimoAno")
                                .HasColumnName("MenorCotacaoUltimoAno");

                            b1.Property<long>("QuantidadeAcoesEmNegociacao")
                                .HasColumnName("QuantidadeAcoesEmNegociacao");

                            b1.Property<string>("Setor")
                                .HasColumnName("Setor");

                            b1.Property<string>("SubSetor")
                                .HasColumnName("SubSetor");

                            b1.Property<string>("TipoPapel")
                                .HasColumnName("TipoPapel");

                            b1.Property<double>("ValorFirma")
                                .HasColumnName("ValorFirma");

                            b1.Property<double>("ValorMercado")
                                .HasColumnName("ValorMercado");

                            b1.ToTable("DadosFundamentalistas");

                            b1.HasOne("AnaliseAcoes.Domain.Entities.DadoFundamentalista")
                                .WithOne("DadosGerais")
                                .HasForeignKey("AnaliseAcoes.Domain.ValueObjects.DadosGerais", "DadoFundamentalistaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
